### ISSUE TITLE
Bad key "text.kerning_factor" - cgn_colored_MNIST

### ISSUE THREAD

**Issue by nudro** [autonomousvision/counterfactual_generative_networks#1]
Thanks for the great code and paper. 

```
python mnists/train_cgn.py --cfg mnists/experiments/cgn_colored_MNIST/cfg.yaml

Bad key "text.kerning_factor" on line 4 in
/home/local/AD/cordun1/anaconda3/envs/gans/lib/python3.7/site-packages/matplotlib/mpl-data/stylelib/_classic_test_patch.mplstyle.
You probably need to get an updated matplotlibrc file from
https://github.com/matplotlib/matplotlib/blob/v3.1.3/matplotlibrc.template
or from the matplotlib source distribution

initialize network with orthogonal
Traceback (most recent call last):
  File "mnists/train_cgn.py", line 179, in <module>
    main(cfg)
  File "mnists/train_cgn.py", line 131, in main
    cfg.TRAIN.WORKERS)
  File "/home/local/AD/cordun1/experiments/causality/counterfactual_generative_networks/mnists/dataloader.py", line 182, in get_dataloaders
    ds_train = MNIST(train=True)
  File "/home/local/AD/cordun1/experiments/causality/counterfactual_generative_networks/mnists/dataloader.py", line 17, in __init__
    data_dic = np.load(self.data_path, encoding='latin1', allow_pickle=True).item()
  File "/home/local/AD/cordun1/anaconda3/envs/gans/lib/python3.7/site-packages/numpy/lib/npyio.py", line 416, in load
    fid = stack.enter_context(open(os_fspath(file), "rb"))
FileNotFoundError: [Errno 2] No such file or directory: 'mnists/data/colored_mnist/mnist_10color_jitter_var_0.020.npy'
```

**Comment by xl-sr** [comment]
Seems like you did not download the data?

Simply run 
```
./scripts/download_data.sh
```

**Comment by ambekarsameer96** [comment]
Hi @xl-sr,
The link in your 
`./scripts/download_data.sh
`
Yields an invalid file:
Output:
`Downloading...
From: https://drive.google.com/u/0/uc?export=download
To: /content/counterfactual_generative_networks/uc?export=download
145B [00:00, 359kB/s]`

**Replacing it with the following link works and yields the required .npy files.** 
`gdown https://drive.google.com/u/0/uc?id=1NSv4RCSHjcHois3dXjYw_PaLIoVlLgXu&export=download
`
Output:
`Downloading...
From: https://drive.google.com/u/0/uc?id=1NSv4RCSHjcHois3dXjYw_PaLIoVlLgXu
To: /content/counterfactual_generative_networks/colored_mnist.tar.gz
100% 38.8M/38.8M [00:00<00:00, 181MB/s] `
